<?php

    // pretty globals for easy links
    define( 'TOP_FOOTER_TEST', 'OUR PROCESS ... YOUR SUCCESS');

    // Bottom Statics Number
    define( 'STATES_NUMBER', 40);                   // OUR STUDENTS ATTEND COLLEGE ALL ACROSS THE U.S.
    define( 'STUDENT_PERCENTAGE', 43);              // STUDENTS PUT ACADEMIC PROGRAMS BEFORE COST & PRESTIGE
    define( 'VISIT_NUMBER', 160);                   // COLLEGE VISITS EACH YEAR BY OUR CONSULTANTS
    define( 'EXPERIENCE_YEAR_NUMBER', 55);          // YEARS OF COMBINED COLLEGE COUNSELING EXPERIENCE
    define( 'CUPS_NUMBER', 1527);                   // CUPS OF COFFEE CONSUMED BY COLLEGE CONNECTORS THIS YEAR
    define( 'FULL_YEAR_COLLEGE_NUMBER', 2278);      // FOUR-YEAR COLLEGES IN THE US (DEGREE-GRANTING, NONPROFIT)
    define( 'PRIVATE_COLLEGE_NUMBER', 1000);        // PRIVATE COLLEGES CHARGE AT LEAST $50,000
    define( 'TEXT_OPTIONAL_COLLEGES_NUMBER', 1000); // COLLEGES ARE TEST-OPTIONAL OR TEST-FLEXIBLE

?>